version: '3.7'

networks:
  frontend:
  backend:

volumes:
  bundle:
  db:
  storage:
  portainer:

services:
  app:
    build:
      context: .
      args:
        IMAGE: ruby:2.6.3-alpine
    stdin_open: true
    tty: true
    volumes:
      - ./src:/app
      - storage:/app/storage
      - bundle:/usr/local/bundle
    networks:
      - backend
    expose:
      - 3000
    depends_on:
      - bundle
      - db
      - selenium
    user: ${CURRENT_UID}

  bundle:
    image: busybox:latest
    volumes:
      - bundle:/usr/local/bundle

  redis:
    image: redis:5-alpine
    command: redis-server --port 6379
    networks:
      - backend
    expose:
      - 6379
    depends_on:
      - app

  db:
    image: postgres:11-alpine
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend
    expose:
      - 5432

  selenium:
    image: selenium/standalone-chrome:latest
    networks:
      - backend
    volumes:
      - /dev/shm:/dev/shm
    expose:
      - 4444

  certs_generator:
    build:
      context: ./certs
      args:
        IMAGE: openjdk:8-jdk-alpine
    volumes:
      - /home/${USER}/certs:/certs

  server:
    build:
      context: ./nginx
      args:
        IMAGE: nginx:1.15-alpine
    networks:
      - frontend
      - backend
    expose:
      - 80
    depends_on:
      - app

  portainer:
    image: portainer/portainer:latest
    command: -H unix:///var/run/docker.sock
    networks:
      - frontend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer:/data
    expose:
      - 9000
