version: '3.7'

volumes:
  db_admin:

services:
  app:
    restart: "no"
    command: rails server -p 3000 -b '0.0.0.0'
    ports:
      - 3000:3000

  redis:
    restart: "no"
    ports:
      - 6379:6379

  db:
    restart: "no"

  db_admin:
    restart: "no"
    image: dpage/pgadmin4:latest
    networks:
      - frontend
      - backend
    volumes:
      - db_admin:/var/lib/pgadmin
    ports:
      - 8000:80
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: admin

  selenium:
    restart: "no"
    ports:
      - 4444:4444

  portainer:
    restart: "no"
    ports:
      - 9000:9000